### ISSUE TITLE
filter customer grids

### ISSUE THREAD

**Issue by luemic** [magento-hackathon/AdvancedAcl#19]

**Comment by himansuahm** [comment]
Create new observe event in etc/config.xml file as below.
<pre><code>
&lt;eav_collection_abstract_load_before&gt;
	&lt;observers&gt;
		&lt;magentohackathon_advancedacl&gt;
			&lt;type&gt;singleton&lt;/type&gt;
			&lt;class&gt;magentohackathon_advancedacl/observer_customer&lt;/class&gt;
			&lt;method&gt;filterCustomerGrid&lt;/method&gt;
		&lt;/magentohackathon_advancedacl&gt;
	&lt;/observers&gt;
&lt;/eav_collection_abstract_load_before>
</code>
</pre>
put above code in adminhtml events.than create new `Customer.php` file in Model/Observer/ as below code.
<pre>
<code>
class MagentoHackathon_AdvancedAcl_Model_Observer_Customer
{
	public function filterCustomerGrid(Varien_Event_Observer $observer) {
		$collection = $observer->getCollection();
		if (!isset($collection)){return;}
        if ($collection instanceof Mage_Customer_Model_Resource_Customer_Collection) {
			$storeIds = $this->getStoreIds();
			if(!empty($storeIds)){$collection->addAttributeToFilter('store_id',$storeIds);}
        }
    }
	protected function getStoreIds()
	{
		return Mage::helper('magentohackathon_advancedacl/data')->getActiveRole()->getStoreIds();
	}
}
</code>
</pre>
